# Main configuration script for Phase 1 (Simulation Phase) of the SpaceNet Testbed
ConstellationName: starlink1020_10_12  # Name must match constellation config file (fakelink6_10_2, onefib66_30_18, starlink72_1_10, starlink72_30_29)
Debug: 0
# Output directory for phase 1 outputs (connectivity matrices, routing tables, etc.)
# Recommended to store outputs in a local repository
OutputFilePath: /home/spacenet/Desktop/jack_results/aiaa_journal/control_noon/london/

# Resource monitoring options (if True: CPU, RAM, etc. data will be collected)
MonitorResource: False

# Source & Destination Nodes for Optimal Routing (For GSes: Total # of Sats + GS # in list; For Sats: idk lol)
SourceNode: 1020
DestNode: 1021

# Routing Algorithm Options
RouteWeight: latency  # Floyd-Warshall Algorithm Weight; Options: 'hops' (default), 'latency', 'distance', 'capacity' 

# Ground Station Options
GroundStationFile: /home/spacenet/simulator/gitlab/dynamic-topology-generator/utils/gs_files/gs_jack_jp.txt
min_elevation_angle: 25 # minimum elevation angle between GS and Sat (default: 25 degrees)
AssociationCritGSL: BASED_ON_DISTANCE_ONLY_MININET
UseWeatherData: True # if True, GSLs will consider weather attenuation effects (weather data provided by OpenWeatherAPI)

# Terrestrial Integration Configuration:
TopoCrit: 0           # (0) ISL; (1) Terrestrial; (2) Both (default=2)
Gateways:
    t2t_gateway_kmz_type: local # Options- local, link
    t2t_gateway_kmz_path: /home/spacenet/simulator/gitlab/dynamic-topology-generator/t2t/gateway_files/UnofficialStarlinkGlobalGatewaysNPoPs_noLinks.kmz
    t2t_dict_output_file: /home/spacenet/simulator/gitlab/dynamic-topology-generator/t2t/gateway_files/t2t_dict.json
Azure: # Configuration for using Azure data center locations for t2t link endpoints
    t2t_use_azure: True
    t2t_azure_endpoint_location_file: /home/spacenet/simulator/gitlab/dynamic-topology-generator/t2t/azure/AzureDataCenterLocations.csv
    t2t_azure_endpoint_latency_url: https://learn.microsoft.com/en-us/azure/networking/azure-network-latency
    t2t_azure_dict_output_file: /home/spacenet/simulator/gitlab/dynamic-topology-generator/t2t/azure/t2t_azure_dict.json
WonderProxy: # Configuration for using WonderProxy server locations for t2t link endpoints
    t2t_use_wonderproxy: True
    t2t_wonderproxy_endpoint_location_file: /home/spacenet/simulator/gitlab/dynamic-topology-generator/t2t/wonderproxy/wonderproxy_servers-2020-07-19.csv
    t2t_wonderproxy_endpoint_latency_file: /home/spacenet/simulator/gitlab/dynamic-topology-generator/t2t/wonderproxy/wonderproxy_pings-2020-07-19-2020-07-20.csv
    t2t_wonderproxy_dict_output_file: /home/spacenet/simulator/gitlab/dynamic-topology-generator/t2t/wonderproxy/t2t_wonderproxy_dict.json
